# Generated by Django 4.2.15 on 2024-08-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_code",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="orderproduct",
            unique_together={("order", "product")},
        ),
    ]
