# Generated by Django 4.2.15 on 2024-09-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_order_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sold_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
